name: predictive_app

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.0.0
  intl: ^0.17.0
  http: ^0.13.5
  flutter_svg: ^1.1.6
  flutter_riverpod: ^2.1.2
  equatable: ^2.0.5
  connectivity_plus: ^3.0.2
  animations: ^2.0.7
  badges: ^2.0.3
  table_calendar: ^3.0.8
  fl_chart: ^0.55.2
  graphic: ^1.0.1
  calendar_date_picker2: ^0.3.6
  flutter_inline_webview_macos: ^0.0.4
  path: ^1.8.2
  csv: ^5.0.1
  syncfusion_flutter_charts: ^20.4.48
  hive: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/data/
    - assets/jsons/
    - assets/web/
  
  fonts:
    - family: AppFontRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: AppFontBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: AppFontItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf

    - family: AppFontlight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

